import { Story } from '@/store/contentStore';

// Sample stories with external media URLs (fallback if API fails)
export const SAMPLE_STORIES: Story[] = [
  {
    id: '1',
    title: 'Journey Through Grief: Finding Light',
    creator: {
      id: 'c1',
      name: 'Dr. Sarah Williams',
      avatar: 'https://i.pravatar.cc/150?img=1',
      bio: 'Grief counselor and mindfulness teacher with 15 years of experience',
      verified: true,
    },
    description: 'A compassionate guide through the stages of grief, offering tools for healing and finding peace.',
    intentions: ['healing', 'resilience'],
    duration: 1620,
    format: 'audio',
    mediaUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400',
    resonanceCount: 2847,
    reflectionPrompts: {
      before: 'What emotions are you carrying with you today?',
      after: 'What moment in this story resonated most deeply with you?',
    },
    tags: ['grief', 'healing', 'loss', 'acceptance'],
    createdAt: '2025-01-15T10:00:00Z',
    isPremium: false,
  },
  {
    id: '2',
    title: 'Building Unshakeable Resilience',
    creator: {
      id: 'c2',
      name: 'Marcus Chen',
      avatar: 'https://i.pravatar.cc/150?img=12',
      bio: 'Former athlete turned life coach, specializing in mental strength',
      verified: true,
    },
    description: 'Learn practical strategies to bounce back from adversity and build mental toughness.',
    intentions: ['resilience', 'growth'],
    duration: 1980,
    format: 'video',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400',
    resonanceCount: 3521,
    reflectionPrompts: {
      before: 'What challenge are you currently facing?',
      after: 'Which resilience practice will you commit to this week?',
    },
    tags: ['resilience', 'strength', 'adversity', 'growth'],
    createdAt: '2025-01-14T14:30:00Z',
    isPremium: false,
  },
  {
    id: '3',
    title: 'Meditation for Deep Inner Peace',
    creator: {
      id: 'c3',
      name: 'Amara Patel',
      avatar: 'https://i.pravatar.cc/150?img=5',
      bio: 'Zen meditation teacher and consciousness explorer',
      verified: true,
    },
    description: 'A guided meditation journey into stillness, helping you discover profound inner calm.',
    intentions: ['mindfulness', 'joy'],
    duration: 1200,
    format: 'audio',
    mediaUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    resonanceCount: 5234,
    reflectionPrompts: {
      before: 'How would you describe your mental state right now?',
      after: 'What did you discover in the silence?',
    },
    tags: ['meditation', 'peace', 'mindfulness', 'calm'],
    createdAt: '2025-01-13T09:00:00Z',
    isPremium: false,
  },
  {
    id: '4',
    title: 'The Art of Self-Love',
    creator: {
      id: 'c4',
      name: 'Isabella Rodriguez',
      avatar: 'https://i.pravatar.cc/150?img=9',
      bio: 'Self-love advocate and relationship coach',
      verified: true,
    },
    description: 'Discover how to cultivate genuine self-love and attract healthier relationships.',
    intentions: ['love', 'growth'],
    duration: 1440,
    format: 'video',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400',
    resonanceCount: 4102,
    reflectionPrompts: {
      before: 'How do you currently show love to yourself?',
      after: 'What self-love practice spoke to your heart?',
    },
    tags: ['self-love', 'relationships', 'boundaries', 'worth'],
    createdAt: '2025-01-12T16:00:00Z',
    isPremium: false,
  },
  {
    id: '5',
    title: 'Morning Gratitude Practice',
    creator: {
      id: 'c5',
      name: 'David Thompson',
      avatar: 'https://i.pravatar.cc/150?img=14',
      bio: 'Positive psychology researcher and gratitude expert',
      verified: true,
    },
    description: 'Start your day with this uplifting gratitude practice that shifts your entire perspective.',
    intentions: ['joy', 'mindfulness'],
    duration: 900,
    format: 'audio',
    mediaUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=400',
    resonanceCount: 6789,
    reflectionPrompts: {
      before: 'What are three things you are grateful for today?',
      after: 'How did focusing on gratitude shift your mood?',
    },
    tags: ['gratitude', 'morning', 'joy', 'positivity'],
    createdAt: '2025-01-11T07:00:00Z',
    isPremium: false,
  },
  {
    id: '6',
    title: 'Transforming Pain into Purpose',
    creator: {
      id: 'c6',
      name: 'Maya Johnson',
      avatar: 'https://i.pravatar.cc/150?img=10',
      bio: 'Life transformation coach and bestselling author',
      verified: true,
    },
    description: 'Learn how to alchemize your deepest wounds into your greatest source of strength and meaning.',
    intentions: ['growth', 'healing'],
    duration: 2100,
    format: 'video',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400',
    resonanceCount: 3890,
    reflectionPrompts: {
      before: 'What past pain are you still carrying?',
      after: 'What purpose might your pain be pointing you toward?',
    },
    tags: ['transformation', 'purpose', 'healing', 'meaning'],
    createdAt: '2025-01-10T13:00:00Z',
    isPremium: true,
    price: 4.99,
  },
];
